filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/lib/tomcat8/logs/*.log
      - /var/log/apache2/*.log
    #Multiline
    multiline.pattern: ^([0-9])
    multiline.negate: true
    multiline.match: after

    tags: ["IRODS_FRONTEND"]

# Disable filebeat monitoring
logging.metrics.enabled: false

output.logstash:
  hosts: ["elk.dh.local:5044"]


